import Vue from 'vue'
import { Button,Form,FormItem,Input,Message,Container,Header,Aside,Main,avatar,dropdown,DropdownMenu,DropdownItem,tag,Menu,MenuItem,Submenu,MenuItemGroup,Collapse,breadcrumb,BreadcrumbItem,Card,Option,Select,Table,TableColumn,Pagination,Switch,Dialog,Col,Row,Avatar,Popconfirm } from 'element-ui'

Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(avatar)
Vue.use(dropdown)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(tag)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(Submenu)
Vue.use(MenuItemGroup)
Vue.use(Collapse)
Vue.use(breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Card)
Vue.use(Option)
Vue.use(Select)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Pagination)
Vue.use(Switch)
Vue.use(Dialog)
Vue.use(Col)
Vue.use(Row)
Vue.use(Avatar)
Vue.use(Popconfirm)

Vue.component(Message.name, Message)
Vue.prototype.$message = Message

